Fix compilation error: Remove unused GeneralSecurityException from revokeAccess method
COMPILATION FIX: Remove GeneralSecurityException from catch clause in revokeAccess()
since we now use static HTTP_TRANSPORT instead of GoogleNetHttpTransport.newTrustedTransport()
which was the source of the GeneralSecurityException.